#*****************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# speech_zybo_project.tcl: Tcl script for re-creating project 'speech_zybo_project'
#
# Generated by Vivado on Mon Jun 22 22:25:48 PDT 2020
# IP Build 2700528 on Thu Nov  7 00:09:20 MST 2019
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (speech_zybo_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo_project/speech_zybo_project.srcs/sources_1/bd/speech_bd/speech_bd.bd"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo_project/speech_zybo_project.srcs/sources_1/bd/speech_bd/hdl/speech_bd_wrapper.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo_project/speech_zybo_project.srcs/constrs_1/new/test_timing.xdc"
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/src/divider.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/controller/controller.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/controller/ctrlrom.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/filter/filter.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/pwmdac/pwmdac.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/source/source.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/spmul/spmul.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/controller/xlat.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/speech256_top/speech256_top.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/src/two_ff_sync.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/controller/controller_tb.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/filter/filter_tb.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/pwmdac/pwmdac_tb.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/sd2dac/sd2dac.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/sd2dac/sd2dac_tb.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/source/source_tb.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/speech256_top/speech256_top_tb.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/spmul/spmul_tb.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/Speech256/verilog/controller/xlat_tb.v"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/constraints/Zybo-Z7-Master.xdc"
#    "/home/siddharth/Data/VivadoProjects/speech_zybo/speech_zybo/sim/AXI_GPIO_tb.sv"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "speech_zybo_project"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "speech_zybo_project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/speech_zybo_project"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z020clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "digilentinc.com:zybo-z7-20:part0:1.0" -objects $obj
set_property -name "board_part_repo_paths" -value "[file normalize "$origin_dir/../../../../.Xilinx/Vivado/2019.2/xhub/board_store"]" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "zybo-z7-20" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "1" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "1" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "1" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "1" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "1" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "1" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "1" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "34" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/ip_repo/speech256_axi_1.0"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/src/divider.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/controller/controller.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/controller/ctrlrom.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/filter/filter.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/pwmdac/pwmdac.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/source/source.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/spmul/spmul.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/controller/xlat.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/speech256_top/speech256_top.v"] \
 [file normalize "${origin_dir}/src/two_ff_sync.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/controller/controller_tb.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/filter/filter_tb.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/pwmdac/pwmdac_tb.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/sd2dac/sd2dac.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/sd2dac/sd2dac_tb.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/source/source_tb.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/speech256_top/speech256_top_tb.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/spmul/spmul_tb.v"] \
 [file normalize "${origin_dir}/Speech256/verilog/controller/xlat_tb.v"] \
]
add_files -norecurse -fileset $obj $files

# Add local files from the original project (-no_copy_sources specified)
#set files [list \
# [file normalize "${origin_dir}/../speech_zybo_project/speech_zybo_project.srcs/sources_1/bd/speech_bd/speech_bd.bd" ]\
# [file normalize "${origin_dir}/../speech_zybo_project/speech_zybo_project.srcs/sources_1/bd/speech_bd/hdl/speech_bd_wrapper.v" ]\
#]
#set added_files [add_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
#set file "speech_bd/speech_bd.bd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "registered_with_manager" -value "1" -objects $file_obj


# Set 'sources_1' fileset properties
#set obj [get_filesets sources_1]
#set_property -name "top" -value "speech_bd_wrapper" -objects $obj
#set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constraints/Zybo-Z7-Master.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constraints/Zybo-Z7-Master.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

set file "[file normalize "$origin_dir/constraints/test_timing.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constraints/test_timing.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
#set file "[file normalize "$origin_dir/../speech_zybo_project/speech_zybo_project.srcs/constrs_1/new/test_timing.xdc"]"
#set file_added [add_files -norecurse -fileset $obj [list $file]]
#set file "new/test_timing.xdc"
#set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
#set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
#set obj [get_filesets constrs_1]
#set_property -name "target_constrs_file" -value "[get_files *new/test_timing.xdc]" -objects $obj
#set_property -name "target_ucf" -value "[get_files *new/test_timing.xdc]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "${origin_dir}/sim/AXI_GPIO_tb.sv"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/sim/AXI_GPIO_tb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "AXI_GPIO_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


source $origin_dir/bd/speech_bd.tcl

set design_name [get_bd_designs]
make_wrapper -files [get_files $design_name.bd] -top -import
