set_clock_groups -logically_exclusive -group [get_clocks -include_generated_clocks {clk_out1_speech_bd_clk_wiz_0_0_1 clkfbout_speech_bd_clk_wiz_0_0_1}] -group [get_clocks -include_generated_clocks {clk_out1_speech_bd_clk_wiz_0_0 clkfbout_speech_bd_clk_wiz_0_0}]
set_clock_groups -logically_exclusive -group [get_clocks -include_generated_clocks divider_0_clk_out] -group [get_clocks -include_generated_clocks divider_0_clk_out_1]
set_clock_groups -asynchronous -group [get_clocks divider_0_clk_out] -group [get_clocks clk_fpga_0]
set_clock_groups -asynchronous -group [get_clocks divider_0_clk_out_1] -group [get_clocks clk_fpga_0]
set_clock_groups -asynchronous -group [get_clocks clk_fpga_0] -group [get_clocks divider_0_clk_out]
set_clock_groups -asynchronous -group [get_clocks clk_fpga_0] -group [get_clocks divider_0_clk_out_1]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
